module.exports = {
    model:         {type: 'string',  role: 'info',              read: true, write: false,                   channel: 'INFO'},           
    id:            {type: 'number',  role: 'info',              read: true, write: false,                   channel: 'INFO'},           
    time:          {type: 'string',  role: 'info',              read: true, write: false,                   channel: 'META'},
    mod:           {type: 'string',  role: 'info',              read: true, write: false,                   channel: 'META'},           
    freq:          {type: 'number',  role: 'info',              read: true, write: false,   unit: 'Hz',     channel: 'META'},
    rssi:          {type: 'number',  role: 'info',              read: true, write: false,   unit: 'dB',     channel: 'META'},
    snr:           {type: 'number',  role: 'info',              read: true, write: false,   unit: 'dB',     channel: 'META'},
    noise:         {type: 'number',  role: 'info',              read: true, write: false,   unit: 'dB',     channel: 'META'},
    cmd:           {type: 'number',  role: 'value',             read: true, write: false,                                  },
    tristate:      {type: 'string',  role: 'value',             read: true, write: false                                   },
    battery_ok:    {type: 'number',  role: 'value.battery',     read: true, write: false                                   },   
    humidity:      {type: 'number',  role: 'value.humidity',    read: true, write: false,   unit: '%',                     },
    temperature_C: {type: 'number',  role: 'value.temperature', read: true, write: false,   unit: '°C',                    },
    temperature_F: {type: 'number',  role: 'value.temperature', read: true, write: false,   unit: '°F',                    },
    pressure_inHg: {type: 'number',  role: 'value.pressure',    read: true, write: false,   unit: 'inHg',                  },
    pressure_hPa:  {type: 'number',  role: 'value.pressure',    read: true, write: false,   unit: 'P',                     },
    channel:       {type: 'string',  role: 'value',             read: true, write: false,                                  },    
};
