module.exports = {
  // Info data
  id:            {type: 'number',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  brand:         {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  model:         {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  subtype:       {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  type:          {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  protocol:      {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'INFO'},           
  // Meta data
  freq:          {type: 'number',  role: 'info',                      read: true, write: false,   unit: 'Hz',     channel: 'META'},
  mic:           {type: 'string',  role: 'value',                     read: true, write: false,                   channel: 'META'},
  mod:           {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'META'},           
  noise:         {type: 'number',  role: 'info',                      read: true, write: false,   unit: 'dB',     channel: 'META'},
  rssi:          {type: 'number',  role: 'info',                      read: true, write: false,   unit: 'dB',     channel: 'META'},
  snr:           {type: 'number',  role: 'info',                      read: true, write: false,   unit: 'dB',     channel: 'META'},
  time:          {type: 'string',  role: 'info',                      read: true, write: false,                   channel: 'META'},
  // general data 
  battery_ok:    {type: 'number',  role: 'value.battery',             read: true, write: false,                                  },   
  battery_mV:    {type: 'number',  role: 'value.battery',             read: true, write: false,   unit: 'mV',                    },   
  button:        {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  button1:       {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  button2:       {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  button3:       {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  button4:       {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  channel:       {type: 'string',  role: 'value',                     read: true, write: false,                                  },    
  cmd:           {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  code:          {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  connected:     {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  counter:       {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  current_A:     {type: 'number',  role: 'value.current',             read: true, write: false,   unit: 'A',                     },
  energy_kWh:    {type: 'number',  role: 'value.power.consumption',   read: true, write: false,   unit: 'kWh',                   },
  event:         {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  extradata:     {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  flags:         {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  heartbeat:     {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  humidity:      {type: 'number',  role: 'value.humidity',            read: true, write: false,   unit: '%',                     },
  learn:         {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  maybe_battery: {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  moisture:      {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  pairing:       {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  power_W:       {type: 'number',  role: 'value.power.consumption',   read: true, write: false,   unit: 'W',                     },
  pressure_hPa:  {type: 'number',  role: 'value.pressure',            read: true, write: false,   unit: 'hPa'                    },
  pressure_inHg: {type: 'number',  role: 'value.pressure',            read: true, write: false,   unit: 'inHg',                  },
  pressure_kPa:  {type: 'number',  role: 'value.pressure',            read: true, write: false,   unit: 'kPa',                   },
  pressure_PSI:  {type: 'number',  role: 'value.pressure',            read: true, write: false,   unit: 'PSI',                   },
  rain_mm:       {type: 'number',  role: 'value.fill',                read: true, write: false,   unit: 'mm',                    },
  repeat:        {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  sequence_num:  {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  seq:           {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  state:         {type: 'string',  role: 'value',                     read: true, write: false,                                  },    
  status:        {type: 'number',  role: 'value',                     read: true, write: false,                                  },    
  storage:       {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  temperature_C: {type: 'number',  role: 'value.temperature',         read: true, write: false,   unit: '°C',                    },
  temperature_F: {type: 'number',  role: 'value.temperature',         read: true, write: false,   unit: '°F',                    },
  transmit:      {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  triggered:     {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  tristate:      {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  unit:          {type: 'string',  role: 'value',                     read: true, write: false,                                  },
  uv:            {type: 'number',  role: 'value',                     read: true, write: false,                                  },
  voltage_V:     {type: 'number',  role: 'value.voltage',             read: true, write: false,   unit: 'V',                     },
  wind_avg_mi_h: {type: 'number',  role: 'value.speed',               read: true, write: false,   unit: 'mph',                   },
  wind_avg_m_s:  {type: 'number',  role: 'value.speed',               read: true, write: false,   unit: 'm/s',                   },
  wind_dir_deg:  {type: 'number',  role: 'value.direction',           read: true, write: false,   unit: '°',                     },
  wind_max_mi_h: {type: 'number',  role: 'value.speed',               read: true, write: false,   unit: 'mph',                   },
  wind_max_m_s:  {type: 'number',  role: 'value.speed',               read: true, write: false,   unit: 'm/s',                   },
};
  