/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'rtl_433 adapter settings': {
        'en': 'Adapter settings for rtl_433',
        'de': 'Adaptereinstellungen für rtl_433',
        'ru': 'Настройки адаптера для rtl_433',
        'pt': 'Configurações do adaptador para rtl_433',
        'nl': 'Adapterinstellingen voor rtl_433',
        'fr': "Paramètres d'adaptateur pour rtl_433",
        'it': "Impostazioni dell'adattatore per rtl_433",
        'es': 'Ajustes del adaptador para rtl_433',
        'pl': 'Ustawienia adaptera dla rtl_433',
        'zh-cn': 'rtl_433的适配器设置'
    },
    "rtl_433": {
        "en": "rtl_433",
        "de": "rtl_433",
        "ru": "rtl_433",
        "pt": "rtl_433",
        "nl": "rtl_433",
        "fr": "rtl_433",
        "it": "rtl_433",
        "es": "rtl_433",
        "pl": "rtl_433",
        "zh-cn": "rtl_433"
    },
    "Options": {
        "en": "Options",
        "de": "Optionen",
        "ru": "Опции",
        "pt": "Opções",
        "nl": "Opties",
        "fr": "Options",
        "it": "Opzioni",
        "es": "Opciones",
        "pl": "Opcje",
        "zh-cn": "选项"
    },
    "Version": {
        "en": "Version",
        "de": "Ausführung",
        "ru": "Версия",
        "pt": "Versão",
        "nl": "Versie",
        "fr": "Version",
        "it": "Versione",
        "es": "Versión",
        "pl": "Wersja",
        "zh-cn": "版本"
    },
    "Protocols": {
        "en": "Protocols",
        "de": "Protokolle",
        "ru": "Протоколы",
        "pt": "Protocolos",
        "nl": "Protocollen",
        "fr": "Protocoles",
        "it": "Protocolli",
        "es": "Protocolos",
        "pl": "Protokoły",
        "zh-cn": "规约"
    },
    "Sensors": {
        "en": "Sensors",
        "de": "Sensoren",
        "ru": "Датчики",
        "pt": "Sensores",
        "nl": "Sensoren",
        "fr": "Capteurs",
        "it": "Sensori",
        "es": "Sensores",
        "pl": "Czujniki",
        "zh-cn": "感测器"
    },
    "include": {
        "en": "include",
        "de": "einschließen",
        "ru": "включают",
        "pt": "incluir",
        "nl": "omvatten",
        "fr": "comprendre",
        "it": "includere",
        "es": "incluir",
        "pl": "zawierać",
        "zh-cn": "包括"
    },
    "level": {
        "en": "level",
        "de": "Niveau",
        "ru": "уровень",
        "pt": "nível",
        "nl": "niveau",
        "fr": "niveau",
        "it": "livello",
        "es": "nivel",
        "pl": "poziom",
        "zh-cn": "等级"
    },
    "spec": {
        "en": "spec",
        "de": "spez",
        "ru": "спецификация",
        "pt": "especificação",
        "nl": "spec",
        "fr": "spec",
        "it": "spec",
        "es": "Especificaciones",
        "pl": "spec",
        "zh-cn": "规格"
    },
    "Device Type": {
        "en": "Device Type",
        "de": "Gerätetyp",
        "ru": "Тип устройства",
        "pt": "Tipo de dispositivo",
        "nl": "Soort apparaat",
        "fr": "Type d'appareil",
        "it": "Tipo di dispositivo",
        "es": "Tipo de dispositivo",
        "pl": "Rodzaj urządzenia",
        "zh-cn": "设备类型"
    },
    "The type of device rtl_433 will connect to": {
        "en": "The type of device rtl_433 will connect to",
        "de": "Der Gerätetyp, mit dem rtl_433 eine Verbindung herstellt",
        "ru": "Тип устройства, к которому будет подключаться rtl_433",
        "pt": "O tipo de dispositivo que rtl_433 se conectará",
        "nl": "Het type apparaat waarmee rtl_433 verbinding maakt",
        "fr": "Le type d'appareil auquel rtl_433 se connectera",
        "it": "Il tipo di dispositivo a cui si connetterà rtl_433",
        "es": "El tipo de dispositivo al que se conectará rtl_433",
        "pl": "Typ urządzenia, z którym będzie się łączyć rtl_433",
        "zh-cn": "设备rtl_433将连接到的类型"
    },
    "Device Index": {
        "en": "Device Index",
        "de": "Geräteindex",
        "ru": "Индекс устройства",
        "pt": "Índice de dispositivo",
        "nl": "Apparaatindex",
        "fr": "Index des appareils",
        "it": "Indice del dispositivo",
        "es": "Índice de dispositivos",
        "pl": "Indeks urządzenia",
        "zh-cn": "设备索引"
    },
    "The index of the device in how rtl_433 natively sees them": {
        "en": "The index of the device in how rtl_433 natively sees them",
        "de": "Der Index des Geräts, in dem rtl_433 sie nativ sieht",
        "ru": "Индекс устройства в том, как rtl_433 нативно их видит",
        "pt": "O índice do dispositivo em como rtl_433 os vê nativamente",
        "nl": "De index van het apparaat in hoe rtl_433 ze native ziet",
        "fr": "L'index de l'appareil dans la façon dont rtl_433 les voit nativement",
        "it": "L'indice del dispositivo nel modo in cui rtl_433 li vede in modo nativo",
        "es": "El índice del dispositivo en cómo rtl_433 los ve de forma nativa",
        "pl": "Indeks urządzenia, w jaki sposób rtl_433 widzi je natywnie",
        "zh-cn": "rtl_433本机如何查看它们的设备索引"
    },
    "USB Port": {
        "en": "USB Port",
        "de": "USB-Anschluss",
        "ru": "USB-порт",
        "pt": "Porta USB",
        "nl": "USB poort",
        "fr": "Port USB",
        "it": "Porta USB",
        "es": "Puerto USB",
        "pl": "Port USB",
        "zh-cn": "USB端口"
    },
    "The specific port for the USB device": {
        "en": "The specific port for the USB device",
        "de": "Der spezifische Anschluss für das USB-Gerät",
        "ru": "Конкретный порт для USB-устройства",
        "pt": "A porta específica para o dispositivo USB",
        "nl": "De specifieke poort voor het USB-apparaat",
        "fr": "Le port spécifique pour le périphérique USB",
        "it": "La porta specifica per il dispositivo USB",
        "es": "El puerto específico para el dispositivo USB",
        "pl": "Określony port dla urządzenia USB",
        "zh-cn": "USB设备的特定端口"
    },
    "SoapySDR query": {
        "en": "SoapySDR query",
        "de": "SoapySDR-Abfrage",
        "ru": "SoapySDR запрос",
        "pt": "Consulta SoapySDR",
        "nl": "SoapySDR-vraag",
        "fr": "Requête SoapySDR",
        "it": "Query SoapySDR",
        "es": "Consulta de SoapySDR",
        "pl": "Zapytanie SoapySDR",
        "zh-cn": "SoapySDR查询"
    },
    "The specific query for the SoapySDR device": {
        "en": "The specific query for the SoapySDR device",
        "de": "Die spezifische Abfrage für das SoapySDR-Gerät",
        "ru": "Конкретный запрос для устройства SoapySDR",
        "pt": "A consulta específica para o dispositivo SoapySDR",
        "nl": "De specifieke vraag voor het SoapySDR-apparaat",
        "fr": "La requête spécifique pour l'appareil SoapySDR",
        "it": "La query specifica per il dispositivo SoapySDR",
        "es": "La consulta específica para el dispositivo SoapySDR",
        "pl": "Konkretne zapytanie dotyczące urządzenia SoapySDR",
        "zh-cn": "SoapySDR设备的特定查询"
    },
    "TCP/IP address": {
        "en": "TCP/IP address",
        "de": "TCP / IP-Adresse",
        "ru": "TCP / IP-адрес",
        "pt": "Endereço TCP / IP",
        "nl": "TCP / IP-adres",
        "fr": "Adresse TCP / IP",
        "it": "Indirizzo TCP / IP",
        "es": "Dirección TCP / IP",
        "pl": "Adres TCP / IP",
        "zh-cn": "TCP / IP地址"
    },
    "The address of the remote device": {
        "en": "The address of the remote device",
        "de": "Die Adresse des Remote-Geräts",
        "ru": "Адрес удаленного устройства",
        "pt": "O endereço do dispositivo remoto",
        "nl": "Het adres van het externe apparaat",
        "fr": "L'adresse de l'appareil distant",
        "it": "L'indirizzo del dispositivo remoto",
        "es": "La dirección del dispositivo remoto",
        "pl": "Adres zdalnego urządzenia",
        "zh-cn": "远端设备的地址"
    },
    "The version found of the rtl_433 program": {
        "en": "The version found of the rtl_433 program",
        "de": "Die gefundene Version des Programms rtl_433",
        "ru": "Найденная версия программы rtl_433",
        "pt": "A versão encontrada do programa rtl_433",
        "nl": "De gevonden versie van het programma rtl_433",
        "fr": "La version trouvée du programme rtl_433",
        "it": "La versione trovata del programma rtl_433",
        "es": "La versión encontrada del programa rtl_433",
        "pl": "Znaleziona wersja programu rtl_433",
        "zh-cn": "找到rtl_433程序的版本"
    },
    "Command line": {
        "en": "Command line",
        "de": "Befehlszeile",
        "ru": "Командная строка",
        "pt": "Linha de comando",
        "nl": "Opdrachtregel",
        "fr": "Ligne de commande",
        "it": "Riga di comando",
        "es": "Línea de comando",
        "pl": "Wiersz poleceń",
        "zh-cn": "命令行"
    },
    "This is how rtl_433 will be invoked (changing values in the protocols and options tabs will change this value)": {
        "en": "This is how rtl_433 will be invoked (changing values in the protocols and options tabs will change this value)",
        "de": "Auf diese Weise wird rtl_433 aufgerufen (durch Ändern der Werte in den Registerkarten Protokolle und Optionen wird dieser Wert geändert).",
        "ru": "Вот как будет вызываться rtl_433 (изменение значений на вкладках протоколов и опций изменит это значение)",
        "pt": "É assim que rtl_433 será chamado (alterar valores nas guias de protocolos e opções irá alterar este valor)",
        "nl": "Dit is hoe rtl_433 wordt aangeroepen (het veranderen van waarden in de protocollen en opties tabbladen zal deze waarde veranderen)",
        "fr": "C'est ainsi que rtl_433 sera appelé (la modification des valeurs dans les onglets protocoles et options changera cette valeur)",
        "it": "Questo è il modo in cui verrà richiamato rtl_433 (la modifica dei valori nelle schede dei protocolli e delle opzioni cambierà questo valore)",
        "es": "Así es como se invocará rtl_433 (el cambio de valores en las pestañas de protocolos y opciones cambiará este valor)",
        "pl": "W ten sposób zostanie wywołany rtl_433 (zmiana wartości w zakładkach protokołów i opcji zmieni tę wartość)",
        "zh-cn": "这就是调用rtl_433的方式（在协议和选项标签中更改值将更改该值）"
    },
    "Testing": {
        "en": "Testing",
        "de": "Testen",
        "ru": "Тестирование",
        "pt": "Testando",
        "nl": "Testen",
        "fr": "Essai",
        "it": "Testing",
        "es": "Pruebas",
        "pl": "Testowanie",
        "zh-cn": "测验"
    },
    "Production": {
        "en": "Production",
        "de": "Produktion",
        "ru": "Производство",
        "pt": "Produção",
        "nl": "Productie",
        "fr": "Production",
        "it": "Produzione",
        "es": "Producción",
        "pl": "Produkcja",
        "zh-cn": "生产"
    },
    "Testing returns all protocols, production returns only the protocols you include": {
        "en": "Testing returns all protocols, production returns only the protocols you include",
        "de": "Beim Testen werden alle Protokolle zurückgegeben, bei der Produktion werden nur die von Ihnen angegebenen Protokolle zurückgegeben",
        "ru": "Тестирование возвращает все протоколы, производство возвращает только те протоколы, которые вы включили",
        "pt": "O teste retorna todos os protocolos, a produção retorna apenas os protocolos incluídos",
        "nl": "Testen retourneert alle protocollen, productie retourneert alleen de protocollen die u opneemt",
        "fr": "Le test renvoie tous les protocoles, la production ne renvoie que les protocoles que vous incluez",
        "it": "Il test restituisce tutti i protocolli, la produzione restituisce solo i protocolli inclusi",
        "es": "Las pruebas devuelven todos los protocolos, la producción devuelve solo los protocolos que incluye",
        "pl": "Testowanie zwraca wszystkie protokoły, produkcja zwraca tylko te protokoły, które uwzględnisz",
        "zh-cn": "测试返回所有协议，生产仅返回您包含的协议"
    },
    "Include Blacklisted": {
        "en": "Include Blacklisted",
        "de": "Blacklisted einschließen",
        "ru": "Включить в черный список",
        "pt": "Incluir na lista negra",
        "nl": "Opnemen op de zwarte lijst",
        "fr": "Inclure la liste noire",
        "it": "Includi nella lista nera",
        "es": "Incluir en la lista negra",
        "pl": "Uwzględnij na czarnej liście",
        "zh-cn": "列入黑名单"
    },
    "Make rtl_433 decode blacklisted or unstable protocols": {
        "en": "Make rtl_433 decode blacklisted or unstable protocols",
        "de": "Lassen Sie rtl_433 Protokolle auf der schwarzen Liste oder instabile Protokolle dekodieren",
        "ru": "Сделайте так, чтобы rtl_433 декодировал протоколы из черного списка или нестабильные протоколы",
        "pt": "Faça rtl_433 decodificar protocolos na lista negra ou instáveis",
        "nl": "Zorg ervoor dat rtl_433 op de zwarte lijst geplaatste of onstabiele protocollen decodeert",
        "fr": "Faire décoder rtl_433 les protocoles sur liste noire ou instables",
        "it": "Fai in modo che rtl_433 decodifichi i protocolli nella lista nera o instabili",
        "es": "Hacer que rtl_433 decodifique protocolos en lista negra o inestables",
        "pl": "Spraw, aby rtl_433 dekodował protokoły z czarnej listy lub niestabilne",
        "zh-cn": "使rtl_433解码列入黑名单或不稳定的协议"
    },
    "Include": {
        "en": "Include",
        "de": "Einschließen",
        "ru": "Включают",
        "pt": "Incluir",
        "nl": "Omvatten",
        "fr": "Comprendre",
        "it": "Includere",
        "es": "Incluir",
        "pl": "Zawierać",
        "zh-cn": "包括"
    },
    "Exclude": {
        "en": "Exclude",
        "de": "Ausschließen",
        "ru": "Исключать",
        "pt": "Excluir",
        "nl": "Uitsluiten",
        "fr": "Exclure",
        "it": "Escludere",
        "es": "Excluir",
        "pl": "Wykluczać",
        "zh-cn": "排除"
    },
    "ID": {
        "en": "ID",
        "de": "ICH WÜRDE",
        "ru": "Я БЫ",
        "pt": "EU IA",
        "nl": "ID kaart",
        "fr": "identifiant",
        "it": "ID",
        "es": "IDENTIFICACIÓN",
        "pl": "ID",
        "zh-cn": "ID"
    },
    "Protocol": {
        "en": "Protocol",
        "de": "Protokoll",
        "ru": "Протокол",
        "pt": "Protocolo",
        "nl": "Protocol",
        "fr": "Protocole",
        "it": "Protocollo",
        "es": "Protocolo",
        "pl": "Protokół",
        "zh-cn": "协议"
    },
    "Gain": {
        "en": "Gain",
        "de": "Dazugewinnen",
        "ru": "Прирост",
        "pt": "Ganho",
        "nl": "Krijgen",
        "fr": "Gagner",
        "it": "Guadagno",
        "es": "Ganar",
        "pl": "Zdobyć",
        "zh-cn": "获得"
    },
    "(default: auto)": {
        "en": "(default: auto)",
        "de": "(Standard: Auto)",
        "ru": "(по умолчанию: авто)",
        "pt": "(padrão: automático)",
        "nl": "(standaard: auto)",
        "fr": "(par défaut: auto)",
        "it": "(impostazione predefinita: auto)",
        "es": "(predeterminado: auto)",
        "pl": "(domyślnie: auto)",
        "zh-cn": "（默认：自动）"
    },
    "settings": {
        "en": "settings",
        "de": "die Einstellungen",
        "ru": "настройки",
        "pt": "definições",
        "nl": "instellingen",
        "fr": "réglages",
        "it": "impostazioni",
        "es": "ajustes",
        "pl": "ustawienia",
        "zh-cn": "设定"
    },
    "apply a list of keyword=value settings for SoapySDR devices": {
        "en": "apply a list of keyword=value settings for SoapySDR devices",
        "de": "Wenden Sie eine Liste der Einstellungen für Schlüsselwort = Wert für SoapySDR-Geräte an",
        "ru": "применить список настроек ключевое слово = значение для устройств SoapySDR",
        "pt": "aplique uma lista de configurações de palavra-chave = valor para dispositivos SoapySDR",
        "nl": "pas een lijst met trefwoord = waarde-instellingen toe voor SoapySDR-apparaten",
        "fr": "appliquer une liste de paramètres mot-clé = valeur pour les appareils SoapySDR",
        "it": "applicare un elenco di parole chiave = impostazioni del valore per i dispositivi SoapySDR",
        "es": "aplicar una lista de configuraciones de palabra clave = valor para dispositivos SoapySDR",
        "pl": "zastosuj listę ustawień słowo kluczowe = wartość dla urządzeń SoapySDR",
        "zh-cn": "应用SoapySDR设备的keyword = value设置列表"
    },
    "Frequency": {
        "en": "Frequency",
        "de": "Frequenz",
        "ru": "Частота",
        "pt": "Frequência",
        "nl": "Frequentie",
        "fr": "La fréquence",
        "it": "Frequenza",
        "es": "Frecuencia",
        "pl": "Częstotliwość",
        "zh-cn": "频率"
    },
    "Receive frequency(s) (default: 433920000 Hz)": {
        "en": "Receive frequency(s) (default: 433920000 Hz)",
        "de": "Empfangsfrequenz (en) (Standard: 433920000 Hz)",
        "ru": "Частота приема (частоты) (по умолчанию: 433920000 Гц)",
        "pt": "Frequência (s) de recepção (padrão: 433920000 Hz)",
        "nl": "Ontvangstfrequentie (s) (standaard: 433920000 Hz)",
        "fr": "Fréquence (s) de réception (par défaut: 433920000 Hz)",
        "it": "Frequenza di ricezione (predefinita: 433920000 Hz)",
        "es": "Frecuencia (s) de recepción (predeterminado: 433920000 Hz)",
        "pl": "Odbieranie częstotliwości (domyślnie: 433920000 Hz)",
        "zh-cn": "接收频率（默认：433920000 Hz）"
    },
    "Seconds": {
        "en": "Seconds",
        "de": "Sekunden",
        "ru": "Секунды",
        "pt": "Segundos",
        "nl": "Seconden",
        "fr": "Secondes",
        "it": "Secondi",
        "es": "Segundos",
        "pl": "sekundy",
        "zh-cn": "秒"
    },
    "Hop interval for polling of multiple frequencies (default: 600 seconds)": {
        "en": "Hop interval for polling of multiple frequencies (default: 600 seconds)",
        "de": "Sprungintervall für die Abfrage mehrerer Frequenzen (Standard: 600 Sekunden)",
        "ru": "Интервал перехода для опроса нескольких частот (по умолчанию: 600 секунд)",
        "pt": "Intervalo de salto para sondagem de múltiplas frequências (padrão: 600 segundos)",
        "nl": "Hop-interval voor polling van meerdere frequenties (standaard: 600 seconden)",
        "fr": "Intervalle de saut pour l'interrogation de plusieurs fréquences (par défaut: 600 secondes)",
        "it": "Intervallo di salto per il polling di più frequenze (predefinito: 600 secondi)",
        "es": "Intervalo de salto para el sondeo de múltiples frecuencias (predeterminado: 600 segundos)",
        "pl": "Interwał przeskoków dla odpytywania wielu częstotliwości (domyślnie: 600 sekund)",
        "zh-cn": "轮询多个频率的跳跃间隔（默认值：600秒）"
    },
    "Include Signal Data": {
        "en": "Include Signal Data",
        "de": "Signaldaten einschließen",
        "ru": "Включить данные сигнала",
        "pt": "Incluir Dados de Sinal",
        "nl": "Signaalgegevens opnemen",
        "fr": "Inclure les données de signal",
        "it": "Includi dati di segnale",
        "es": "Incluir datos de señal",
        "pl": "Uwzględnij dane sygnałowe",
        "zh-cn": "包括信号数据"
    },
    "Include Protocol Data": {
        "en": "Include Protocol Data",
        "de": "Protokolldaten einschließen",
        "ru": "Включить данные протокола",
        "pt": "Incluir dados de protocolo",
        "nl": "Inclusief protocolgegevens",
        "fr": "Inclure les données de protocole",
        "it": "Includi dati di protocollo",
        "es": "Incluir datos de protocolo",
        "pl": "Dołącz dane protokołu",
        "zh-cn": "包括协议数据"
    },
    "Create fields in the sensor object for signal data": {
        "en": "Create fields in the sensor object for signal data",
        "de": "Erstellen Sie im Sensorobjekt Felder für Signaldaten",
        "ru": "Создайте поля в объекте датчика для данных сигнала",
        "pt": "Crie campos no objeto sensor para dados de sinal",
        "nl": "Maak velden in het sensorobject voor signaalgegevens",
        "fr": "Créer des champs dans l'objet capteur pour les données de signal",
        "it": "Creare campi nell'oggetto sensore per i dati del segnale",
        "es": "Crear campos en el objeto sensor para datos de señales.",
        "pl": "Utwórz pola w obiekcie czujnika dla danych sygnałowych",
        "zh-cn": "在传感器对象中创建字段以获取信号数据"
    },
    "Create fields in the sensor object for protocol data": {
        "en": "Create fields in the sensor object for protocol data",
        "de": "Erstellen Sie im Sensorobjekt Felder für Protokolldaten",
        "ru": "Создайте поля в объекте датчика для данных протокола",
        "pt": "Crie campos no objeto sensor para dados de protocolo",
        "nl": "Maak velden in het sensorobject voor protocolgegevens",
        "fr": "Créer des champs dans l'objet capteur pour les données de protocole",
        "it": "Creare campi nell'oggetto sensore per i dati del protocollo",
        "es": "Crear campos en el objeto sensor para datos de protocolo",
        "pl": "Utwórz pola w obiekcie czujnika dla danych protokołu",
        "zh-cn": "在传感器对象中为协议数据创建字段"
    },
    "Time elapsed without an update to declare sensor dead": {
        "en": "Time elapsed without an update to declare sensor dead",
        "de": "Ohne Aktualisierung verstrichene Zeit, um den Sensor für tot zu erklären",
        "ru": "Прошло время без обновления, чтобы объявить датчик неисправным",
        "pt": "Tempo decorrido sem uma atualização para declarar sensor morto",
        "nl": "De tijd is verstreken zonder een update om de sensor dood te verklaren",
        "fr": "Temps écoulé sans mise à jour pour déclarer le capteur mort",
        "it": "Tempo trascorso senza un aggiornamento per dichiarare il sensore guasto",
        "es": "Tiempo transcurrido sin una actualización para declarar el sensor muerto",
        "pl": "Czas, który upłynął bez aktualizacji, aby uznać czujnik za martwy",
        "zh-cn": "经过时间而未进行更新以声明传感器已失效"
    },
    "Determines the unit of measure data comes back in, automatically set by your system.config": {
        "en": "Determines the unit of measure data comes back in, automatically set by your system.config",
        "de": "Legt fest, welche Maßeinheitsdaten zurückkommen und automatisch von Ihrer system.config festgelegt werden",
        "ru": "Определяет возвращаемую единицу измерения данных, автоматически устанавливается вашей system.config",
        "pt": "Determina a unidade de medida de retorno dos dados, definida automaticamente por seu system.config",
        "nl": "Bepaalt de maateenheid die de gegevens weer binnenkomen, automatisch ingesteld door uw system.config",
        "fr": "Détermine l'unité de mesure des données qui revient, automatiquement définie par votre système.",
        "it": "Determina l'unità di misura dei dati di ritorno, impostata automaticamente dal tuo system.config",
        "es": "Determina la unidad de medida en la que vuelven los datos, configurada automáticamente por su sistema.",
        "pl": "Określa jednostkę miary, w której dane wracają, automatycznie ustawiane przez plik system.config",
        "zh-cn": "确定返回的度量单位数据，由system.config自动设置"
    },
    "Manual detection level used to determine pulses (-1.0 to -30.0) (0=auto)": {
        "en": "Manual detection level used to determine pulses (-1.0 to -30.0) (0=auto)",
        "de": "Manuelle Erkennungsstufe zur Bestimmung der Impulse (-1,0 bis -30,0) (0 = automatisch)",
        "ru": "Уровень обнаружения вручную, используемый для определения импульсов (от -1,0 до -30,0) (0 = авто)",
        "pt": "Nível de detecção manual usado para determinar pulsos (-1,0 a -30,0) (0 = automático)",
        "nl": "Handmatig detectieniveau gebruikt om pulsen te bepalen (-1,0 tot -30,0) (0 = auto)",
        "fr": "Niveau de détection manuel utilisé pour déterminer les impulsions (-1,0 à -30,0) (0 = auto)",
        "it": "Livello di rilevamento manuale utilizzato per determinare gli impulsi (da -1,0 a -30,0) (0 = auto)",
        "es": "Nivel de detección manual utilizado para determinar pulsos (-1,0 a -30,0) (0 = automático)",
        "pl": "Ręczny poziom wykrywania używany do określania impulsów (od -1,0 do -30,0) (0 = auto)",
        "zh-cn": "用于确定脉冲的手动检测级别（-1.0至-30.0）（0 =自动）"
    },
    "Add a general purpose decoder (prepend -R 0 to disable all decoders)": {
        "en": "Add a general purpose decoder (prepend -R 0 to disable all decoders)",
        "de": "Fügen Sie einen Allzweckdecoder hinzu (stellen Sie -R 0 voran, um alle Decoder zu deaktivieren).",
        "ru": "Добавьте декодер общего назначения (добавьте -R 0, чтобы отключить все декодеры)",
        "pt": "Adicione um decodificador de uso geral (prefixe -R 0 para desativar todos os decodificadores)",
        "nl": "Voeg een decoder voor algemeen gebruik toe (voeg -R 0 toe om alle decoders uit te schakelen)",
        "fr": "Ajouter un décodeur à usage général (préfixez -R 0 pour désactiver tous les décodeurs)",
        "it": "Aggiungi un decodificatore generico (aggiungi -R 0 per disabilitare tutti i decodificatori)",
        "es": "Agregue un decodificador de propósito general (anteponga -R 0 para deshabilitar todos los decodificadores)",
        "pl": "Dodaj dekoder ogólnego przeznaczenia (dołącz -R 0 na początku, aby wyłączyć wszystkie dekodery)",
        "zh-cn": "添加通用解码器（在前缀-R 0之前禁用所有解码器）"
    },
    "Sample Rate": {
        "en": "Sample Rate",
        "de": "Beispielrate",
        "ru": "Частота дискретизации",
        "pt": "Taxa de amostragem",
        "nl": "Bemonsteringsfrequentie",
        "fr": "Taux d'échantillonnage",
        "it": "Frequenza di campionamento",
        "es": "Frecuencia de muestreo",
        "pl": "Próbna stawka",
        "zh-cn": "采样率"
    },
    "Set sample rate (default: 250000 Hz)": {
        "en": "Set sample rate (default: 250000 Hz)",
        "de": "Samplerate einstellen (Standard: 250000 Hz)",
        "ru": "Установить частоту дискретизации (по умолчанию: 250000 Гц)",
        "pt": "Definir taxa de amostragem (padrão: 250000 Hz)",
        "nl": "Bemonsteringsfrequentie instellen (standaard: 250000 Hz)",
        "fr": "Définir la fréquence d'échantillonnage (par défaut: 250000 Hz)",
        "it": "Imposta la frequenza di campionamento (impostazione predefinita: 250000 Hz)",
        "es": "Establecer frecuencia de muestreo (predeterminado: 250000 Hz)",
        "pl": "Ustaw częstotliwość próbkowania (domyślnie: 250000 Hz)",
        "zh-cn": "设置采样率（默认：250000 Hz）"
    },
    "PPM Error": {
        "en": "PPM Error",
        "de": "PPM-Fehler",
        "ru": "Ошибка PPM",
        "pt": "Erro PPM",
        "nl": "PPM-fout",
        "fr": "Erreur PPM",
        "it": "Errore PPM",
        "es": "Error de PPM",
        "pl": "Błąd PPM",
        "zh-cn": "PPM错误"
    },
    "Correct rtl-sdr tuner frequency offset error (default: 0)": {
        "en": "Correct rtl-sdr tuner frequency offset error (default: 0)",
        "de": "Korrigieren Sie den Frequenzversatzfehler des RTL-SDR-Tuners (Standard: 0).",
        "ru": "Исправить ошибку сдвига частоты тюнера rtl-sdr (по умолчанию: 0)",
        "pt": "Corrigir erro de deslocamento de frequência do sintonizador rtl-sdr (padrão: 0)",
        "nl": "Correcte rtl-sdr tuner frequentie offset fout (standaard: 0)",
        "fr": "Correction de l'erreur de décalage de fréquence du tuner RTL-SDR (par défaut: 0)",
        "it": "Correggere l'errore di offset della frequenza del sintonizzatore rtl-sdr (default: 0)",
        "es": "Corregir error de compensación de frecuencia del sintonizador rtl-sdr (predeterminado: 0)",
        "pl": "Popraw błąd przesunięcia częstotliwości tunera RTL-SDR (domyślnie: 0)",
        "zh-cn": "正确的rtl-sdr调谐器频率偏移错误（默认值：0）"
    },
    "Unit of Measure": {
        "en": "Unit of Measure",
        "de": "Maßeinheit",
        "ru": "Единица измерения",
        "pt": "Unidade de medida",
        "nl": "Maateenheid",
        "fr": "Unité de mesure",
        "it": "Unità di misura",
        "es": "Unidad de medida",
        "pl": "Jednostka miary",
        "zh-cn": "测量单位"
    },
    "device timeout": {
        "en": "device timeout",
        "de": "Geräte-Timeout",
        "ru": "тайм-аут устройства",
        "pt": "tempo limite do dispositivo",
        "nl": "time-out van het apparaat",
        "fr": "délai d'expiration de l'appareil",
        "it": "timeout del dispositivo",
        "es": "tiempo de espera del dispositivo",
        "pl": "limit czasu urządzenia",
        "zh-cn": "设备超时"
    },
    "Period of time between scans to determine if the sensor is still alive": {
        "en": "Period of time between scans to determine if the sensor is still alive",
        "de": "Zeitraum zwischen den Scans, um festzustellen, ob der Sensor noch am Leben ist",
        "ru": "Период времени между сканированиями, чтобы определить, жив ли датчик",
        "pt": "Período de tempo entre as varreduras para determinar se o sensor ainda está ativo",
        "nl": "Tijdsperiode tussen scans om te bepalen of de sensor nog in leven is",
        "fr": "Période de temps entre les analyses pour déterminer si le capteur est toujours en vie",
        "it": "Periodo di tempo tra le scansioni per determinare se il sensore è ancora attivo",
        "es": "Período de tiempo entre exploraciones para determinar si el sensor todavía está activo",
        "pl": "Okres czasu między skanami w celu ustalenia, czy czujnik nadal żyje",
        "zh-cn": "两次扫描之间的时间间隔，以确定传感器是否仍在运行"
    },
    "kill check interval": {
        "en": "kill check interval",
        "de": "Kill Check Intervall",
        "ru": "убить интервал проверки",
        "pt": "intervalo de verificação de morte",
        "nl": "kill check-interval",
        "fr": "intervalle de contrôle de mise à mort",
        "it": "kill intervallo di controllo",
        "es": "matar intervalo de verificación",
        "pl": "interwał sprawdzania zabicia",
        "zh-cn": "取消检查间隔"
    },
    "Create objects for newly detected sensors": {
        "en": "Create objects for newly detected sensors",
        "de": "Erstellen Sie Objekte für neu erkannte Sensoren",
        "ru": "Создавать объекты для вновь обнаруженных датчиков",
        "pt": "Crie objetos para sensores recém-detectados",
        "nl": "Maak objecten voor nieuw gedetecteerde sensoren",
        "fr": "Créer des objets pour les capteurs nouvellement détectés",
        "it": "Crea oggetti per i sensori appena rilevati",
        "es": "Crea objetos para sensores recién detectados",
        "pl": "Utwórz obiekty dla nowo wykrytych czujników",
        "zh-cn": "为新检测到的传感器创建对象"
    },
    "Could not execute rtl_433, permission errors?": {
        "en": "Could not execute rtl_433, permission errors?",
        "de": "Konnte rtl_433, Berechtigungsfehler nicht ausführen?",
        "ru": "Не удалось выполнить rtl_433, ошибки разрешения?",
        "pt": "Não foi possível executar rtl_433, erros de permissão?",
        "nl": "Kan rtl_433, toestemmingsfouten niet uitvoeren?",
        "fr": "Impossible d'exécuter rtl_433, erreurs d'autorisation?",
        "it": "Impossibile eseguire rtl_433, errori di autorizzazione?",
        "es": "No se pudo ejecutar rtl_433, ¿errores de permiso?",
        "pl": "Nie można wykonać rtl_433, błędy uprawnień?",
        "zh-cn": "无法执行rtl_433，权限错误？"
    },
    "Could not find rtl_433 executable": {
        "en": "Could not find rtl_433 executable",
        "de": "Die ausführbare Datei rtl_433 konnte nicht gefunden werden",
        "ru": "Не удалось найти исполняемый файл rtl_433",
        "pt": "Não foi possível encontrar o executável rtl_433",
        "nl": "Kan uitvoerbaar bestand rtl_433 niet vinden",
        "fr": "Impossible de trouver l'exécutable rtl_433",
        "it": "Impossibile trovare l'eseguibile rtl_433",
        "es": "No se pudo encontrar el ejecutable rtl_433",
        "pl": "Nie można znaleźć pliku wykonywalnego rtl_433",
        "zh-cn": "找不到rtl_433可执行文件"
    },
    "General error executing rtl_433": {
        "en": "General error executing rtl_433",
        "de": "Allgemeiner Fehler beim Ausführen von rtl_433",
        "ru": "Общая ошибка при выполнении rtl_433",
        "pt": "Erro geral ao executar rtl_433",
        "nl": "Algemene fout bij het uitvoeren van rtl_433",
        "fr": "Erreur générale lors de l'exécution de rtl_433",
        "it": "Errore generale durante l'esecuzione di rtl_433",
        "es": "Error general al ejecutar rtl_433",
        "pl": "Ogólny błąd podczas wykonywania rtl_433",
        "zh-cn": "执行rtl_433时出现一般错误"
    },
    "Not available": {
        "en": "Not available",
        "de": "Nicht verfügbar",
        "ru": "Нет в наличии",
        "pt": "Não disponível",
        "nl": "Niet beschikbaar",
        "fr": "Pas disponible",
        "it": "Non disponibile",
        "es": "No disponible",
        "pl": "Niedostępne",
        "zh-cn": "无法使用"
    },
    "de-duplicate readings": {
        "en": "de-duplicate readings",
        "de": "Deduplizieren von Messwerten",
        "ru": "дедублировать показания",
        "pt": "deduplicar leituras",
        "nl": "ontdubbelen van metingen",
        "fr": "dédupliquer les lectures",
        "it": "letture deduplicate",
        "es": "lecturas duplicadas",
        "pl": "deduplikaty odczytów",
        "zh-cn": "重复读数"
    },
    "Record only changed values": {
        "en": "Record only changed values",
        "de": "Nur geänderte Werte aufzeichnen",
        "ru": "Записывать только измененные значения",
        "pt": "Registrar apenas valores alterados",
        "nl": "Alleen gewijzigde waarden opnemen",
        "fr": "Enregistrer uniquement les valeurs modifiées",
        "it": "Registra solo i valori modificati",
        "es": "Registrar solo valores modificados",
        "pl": "Zapisz tylko zmienione wartości",
        "zh-cn": "仅记录更改的值"
    }
};